version: '3'
services:
  bwp-server:
    image: bwpcontainerregistry.azurecr.io/bwp-server
    ports:
      - 3000:3000
    env_file:
      - .env.production
    networks:
      - social-intranet

  bwp-mail-server:
    image: bwpcontainerregistry.azurecr.io/bwp-mail-server
    ports:
      - 3001:3001
    env_file:
      - .env.production
    networks:
      - social-intranet

  bwp-fe:
    image: bwpcontainerregistry.azurecr.io/bwp-fe
    ports:
      - 80:80
    networks:
      - social-intranet

networks:
  social-intranet:
    driver: bridge
