version: '3'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - social-intranet
  test-db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - social-intranet
  # bwp-server:
  #  image: bwpcontainerregistry.azurecr.io/bwp-server
  #  ports:
  #    - 3000:3000
  #  env_file:
  #    - .env.production
  #  networks:
  #    - social-intranet

  # bwp-mail-server:
  #  image: bwpcontainerregistry.azurecr.io/bwp-mail-server
  #  ports:
  #    - 3001:3001
  #  env_file:
  #    - .env.production
  #  networks:
  #    - social-intranet

  # bwp-fe:
  #   image: bwpcontainerregistry.azurecr.io/bwp-fe
  #   ports:
  #     - 4200:4200
  #   networks:
  #     - social-intranet

networks:
  social-intranet:
    driver: bridge
